services:
  demo_db:
    image: postgres:15
    container_name: demo_database
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5200:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube
    container_name: demo_sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  db_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: