name: Schedule Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: |
          echo "Hello World!"
